/**
 * iQuizPros — Firebase Cloud Functions
 *
 * Exports:
 *   generateQuiz          — AI quiz generation via Google Gemini
 *   getUserUsageStats     — Monthly usage / rate-limit info for the calling user
 *   getGeneratedQuiz      — Fetch a previously generated quiz by ID
 *   listUserQuizzes       — List all quizzes generated by the calling user
 *   deleteGeneratedQuiz   — Delete a generated quiz document
 *   generateAdaptiveQuestion — Generate a single follow-up question for live sessions
 *   stripeWebhook         — Stripe subscription lifecycle webhook (HTTP, not callable)
 *
 * Region: europe-west2 (London)
 * Node runtime: 18
 */

'use strict';

const functions                  = require('firebase-functions/v1');
const { defineSecret }           = require('firebase-functions/params');
const admin                      = require('firebase-admin');
const { GoogleGenerativeAI }     = require('@google/generative-ai');
const stripe                     = require('stripe');

admin.initializeApp();
const db = admin.firestore();

const REGION = 'europe-west2';

// ---------------------------------------------------------------------------
// Secret definitions (stored in Google Cloud Secret Manager)
// Set with: firebase functions:secrets:set GEMINI_KEY
// ---------------------------------------------------------------------------
const GEMINI_KEY            = defineSecret('GEMINI_KEY');
const STRIPE_SECRET         = defineSecret('STRIPE_SECRET');
const STRIPE_WEBHOOK_SECRET = defineSecret('STRIPE_WEBHOOK_SECRET');

// ---------------------------------------------------------------------------
// Admin UID — this user bypasses all rate limits
// ---------------------------------------------------------------------------
const ADMIN_UID = '93fNHZN5u7YLk5ITbPTHfsFYTI13';

// ---------------------------------------------------------------------------
// Rate-limit tiers (updated v3.2 pricing)
// null = truly unlimited
// ---------------------------------------------------------------------------
const RATE_LIMITS = {
  free:      5,    // Basic free tier — 5 generations/month
  premium:   100,  // Premium tier — 100 generations/month ($12.99/mo)
  pro:       500,  // Pro tier — 500 generations/month ($29.99/mo)
  unlimited: null  // Kept for backward-compat with existing 'unlimited' subscribers
};

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Returns the subscription tier string for a UID ('free' by default). */
async function getUserTier(uid) {
  const doc = await db.collection('users').doc(uid).get();
  if (!doc.exists) return 'free';
  return doc.data()?.subscription?.tier || 'free';
}

/** Returns the number of AI quiz generations used this calendar month. */
async function getMonthlyUsage(uid) {
  const now      = new Date();
  const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const ref      = db.collection('users').doc(uid).collection('usage').doc(monthKey);
  const doc      = await ref.get();
  return doc.exists ? (doc.data().quizGenerations || 0) : 0;
}

/** Atomically increments the quiz-generation counter for the current month. */
async function incrementMonthlyUsage(uid) {
  const now      = new Date();
  const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const ref      = db.collection('users').doc(uid).collection('usage').doc(monthKey);
  await ref.set(
    { quizGenerations: admin.firestore.FieldValue.increment(1) },
    { merge: true }
  );
}

// ---------------------------------------------------------------------------
// generateQuiz
// ---------------------------------------------------------------------------
exports.generateQuiz = functions.region(REGION).https.onCall({ secrets: [GEMINI_KEY] }, async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Authentication required.');
  }

  const uid = context.auth.uid;
  const {
    topic,
    questionCount = 10,
    difficulty    = 'medium',
    style         = 'multiple-choice',
    promptPrefix  = ''
  } = data;

  const safePrefix = String(promptPrefix || '').slice(0, 300);

  if (!topic) {
    throw new functions.https.HttpsError('invalid-argument', 'topic is required.');
  }
  if (questionCount < 1 || questionCount > 30) {
    throw new functions.https.HttpsError('invalid-argument', 'questionCount must be between 1 and 30.');
  }

  // Rate-limit check (admin is exempt)
  const isAdmin   = (uid === ADMIN_UID);
  const tier      = isAdmin ? 'enterprise' : await getUserTier(uid);
  const limit     = isAdmin ? null : (RATE_LIMITS[tier] !== undefined ? RATE_LIMITS[tier] : RATE_LIMITS.free);
  const used      = isAdmin ? 0    : await getMonthlyUsage(uid);

  if (!isAdmin && limit !== null && used >= limit) {
    const upgradeMsg = tier === 'free'
      ? 'Upgrade to Premium for 100 generations/month.'
      : 'Upgrade to Pro for 500 generations/month.';
    throw new functions.https.HttpsError('resource-exhausted', `Monthly limit reached. ${upgradeMsg}`);
  }

  // Gemini API call
  const genAI = new GoogleGenerativeAI(GEMINI_KEY.value());
  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

  const prompt = `Generate a quiz about "${topic}" with exactly ${questionCount} questions.

Requirements:
- Difficulty: ${difficulty}
- Style: ${style}
- Each question must have exactly 4 options
- Exactly one correct answer per question (correctIndex is 0-based)
- Return ONLY valid JSON — no markdown, no explanation, no code fences

JSON format:
{
  "title": "Quiz title here",
  "questions": [
    {
      "id": 1,
      "question": "Question text?",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "correctIndex": 0,
      "explanation": "Brief explanation of why this is correct"
    }
  ]
}`;

  const fullPrompt = safePrefix ? `${safePrefix}\n\n${prompt}` : prompt;

  let quizData;
  try {
    const result   = await model.generateContent(fullPrompt);
    const raw      = result.response.text().trim();
    const jsonText = raw.replace(/^```json?\s*/i, '').replace(/\s*```$/, '');
    quizData       = JSON.parse(jsonText);
  } catch (err) {
    functions.logger.error('Gemini generateQuiz failed', err);
    throw new functions.https.HttpsError('internal', 'Failed to generate quiz. Please try again.');
  }

  if (!Array.isArray(quizData.questions) || quizData.questions.length === 0) {
    throw new functions.https.HttpsError('internal', 'Invalid quiz format returned by AI.');
  }

  // Persist to Firestore
  const quizDoc = {
    uid,
    title:         quizData.title || `${topic} Quiz`,
    topic,
    difficulty,
    style,
    questions:     quizData.questions,
    questionCount: quizData.questions.length,
    createdAt:     admin.firestore.FieldValue.serverTimestamp()
  };
  const docRef   = await db.collection('generatedQuizzes').add(quizDoc);
  if (!isAdmin) await incrementMonthlyUsage(uid);  // admin usage never counted

  const newUsed   = isAdmin ? 0 : used + 1;
  const remaining = (isAdmin || limit === null) ? null : Math.max(0, limit - newUsed);

  return {
    success: true,
    quiz: {
      id:            docRef.id,
      title:         quizDoc.title,
      topic:         quizDoc.topic,
      questions:     quizDoc.questions,
      questionCount: quizDoc.questionCount
    },
    usage: { used: newUsed, limit, remaining, tier }
  };
});

// ---------------------------------------------------------------------------
// getUserUsageStats
// ---------------------------------------------------------------------------
exports.getUserUsageStats = functions.region(REGION).https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Authentication required.');
  }

  const uid       = context.auth.uid;
  const isAdmin   = (uid === ADMIN_UID);
  const tier      = isAdmin ? 'enterprise' : await getUserTier(uid);
  const used      = isAdmin ? 0            : await getMonthlyUsage(uid);
  const limit     = isAdmin ? null         : (RATE_LIMITS[tier] !== undefined ? RATE_LIMITS[tier] : RATE_LIMITS.free);
  const remaining = (isAdmin || limit === null) ? null : Math.max(0, limit - used);

  return {
    success: true,
    currentLimit: { used, limit, remaining, tier }
  };
});

// ---------------------------------------------------------------------------
// getGeneratedQuiz
// ---------------------------------------------------------------------------
exports.getGeneratedQuiz = functions.region(REGION).https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Authentication required.');
  }

  const { quizId } = data;
  if (!quizId) {
    throw new functions.https.HttpsError('invalid-argument', 'quizId is required.');
  }

  const doc = await db.collection('generatedQuizzes').doc(quizId).get();
  if (!doc.exists) {
    throw new functions.https.HttpsError('not-found', 'Quiz not found.');
  }
  if (doc.data().uid !== context.auth.uid) {
    throw new functions.https.HttpsError('permission-denied', 'Access denied.');
  }

  return { success: true, quiz: { id: doc.id, ...doc.data() } };
});

// ---------------------------------------------------------------------------
// listUserQuizzes
// ---------------------------------------------------------------------------
exports.listUserQuizzes = functions.region(REGION).https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Authentication required.');
  }

  const uid      = context.auth.uid;
  const snapshot = await db.collection('generatedQuizzes')
    .where('uid', '==', uid)
    .orderBy('createdAt', 'desc')
    .limit(50)
    .get();

  const quizzes = snapshot.docs.map(doc => ({
    id:            doc.id,
    title:         doc.data().title,
    topic:         doc.data().topic,
    questionCount: doc.data().questionCount,
    createdAt:     doc.data().createdAt
  }));

  return { success: true, quizzes };
});

// ---------------------------------------------------------------------------
// deleteGeneratedQuiz
// ---------------------------------------------------------------------------
exports.deleteGeneratedQuiz = functions.region(REGION).https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Authentication required.');
  }

  const { quizId } = data;
  if (!quizId) {
    throw new functions.https.HttpsError('invalid-argument', 'quizId is required.');
  }

  const doc = await db.collection('generatedQuizzes').doc(quizId).get();
  if (!doc.exists) {
    throw new functions.https.HttpsError('not-found', 'Quiz not found.');
  }
  if (doc.data().uid !== context.auth.uid) {
    throw new functions.https.HttpsError('permission-denied', 'Access denied.');
  }

  await doc.ref.delete();
  return { success: true };
});

// ---------------------------------------------------------------------------
// generateAdaptiveQuestion
// ---------------------------------------------------------------------------
exports.generateAdaptiveQuestion = functions.region(REGION).https.onCall({ secrets: [GEMINI_KEY] }, async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Authentication required.');
  }

  const {
    topic,
    previousQuestions = [],
    difficulty        = 'medium'
  } = data;

  if (!topic) {
    throw new functions.https.HttpsError('invalid-argument', 'topic is required.');
  }

  const genAI = new GoogleGenerativeAI(GEMINI_KEY.value());
  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

  const prevNote = previousQuestions.length > 0
    ? `\nPreviously asked (do NOT repeat): ${previousQuestions.slice(-10).join('; ')}`
    : '';

  const prompt = `Generate a single ${difficulty} multiple-choice question about "${topic}".${prevNote}

Return ONLY valid JSON — no markdown, no code fences:
{
  "question": "Question text?",
  "options": ["Option A", "Option B", "Option C", "Option D"],
  "correctIndex": 0,
  "explanation": "Brief explanation"
}`;

  try {
    const result   = await model.generateContent(prompt);
    const raw      = result.response.text().trim();
    const jsonText = raw.replace(/^```json?\s*/i, '').replace(/\s*```$/, '');
    const question = JSON.parse(jsonText);
    return { success: true, question };
  } catch (err) {
    functions.logger.error('generateAdaptiveQuestion failed', err);
    throw new functions.https.HttpsError('internal', 'Failed to generate question. Please try again.');
  }
});

// ---------------------------------------------------------------------------
// stripeWebhook  (HTTP — not callable; Stripe posts raw body here)
// ---------------------------------------------------------------------------
exports.stripeWebhook = functions.region(REGION)
  .https.onRequest({ secrets: [STRIPE_SECRET, STRIPE_WEBHOOK_SECRET] }, async (req, res) => {
  const stripeClient  = stripe(STRIPE_SECRET.value());
  const webhookSecret = STRIPE_WEBHOOK_SECRET.value();

  // Verify Stripe signature
  let event;
  try {
    event = stripeClient.webhooks.constructEvent(
      req.rawBody,
      req.headers['stripe-signature'],
      STRIPE_WEBHOOK_SECRET.value()
    );
  } catch (err) {
    functions.logger.error('Stripe webhook signature verification failed', err);
    return res.status(400).send(`Webhook Error: ${err.message}`);
  }

  const obj = event.data.object;

  try {
    switch (event.type) {

      case 'checkout.session.completed': {
        // Payment Links pass the Firebase UID via client_reference_id
        // Custom Checkout fallback: metadata.uid
        const uid  = obj.client_reference_id || obj.metadata?.uid;
        const tier = obj.metadata?.tier || 'premium';
        if (!uid) {
          functions.logger.warn('checkout.session.completed missing uid in metadata', obj.id);
          break;
        }
        await db.collection('users').doc(uid).set({
          subscription: {
            tier,
            stripeCustomerId: obj.customer,
            subscriptionId:   obj.subscription,
            updatedAt:        admin.firestore.FieldValue.serverTimestamp()
          }
        }, { merge: true });
        functions.logger.info(`Subscription activated: uid=${uid} tier=${tier}`);
        break;
      }

      case 'customer.subscription.updated': {
        const customerId = obj.customer;
        const status     = obj.status; // 'active', 'past_due', 'canceled', etc.
        const snap       = await db.collection('users')
          .where('subscription.stripeCustomerId', '==', customerId)
          .limit(1).get();
        if (!snap.empty) {
          const tier = status === 'active' ? (obj.metadata?.tier || 'premium') : 'free';
          await snap.docs[0].ref.set({
            subscription: { tier, updatedAt: admin.firestore.FieldValue.serverTimestamp() }
          }, { merge: true });
          functions.logger.info(`Subscription updated: customerId=${customerId} status=${status} tier=${tier}`);
        }
        break;
      }

      case 'customer.subscription.deleted': {
        const customerId = obj.customer;
        const snap       = await db.collection('users')
          .where('subscription.stripeCustomerId', '==', customerId)
          .limit(1).get();
        if (!snap.empty) {
          await snap.docs[0].ref.set({
            subscription: { tier: 'free', updatedAt: admin.firestore.FieldValue.serverTimestamp() }
          }, { merge: true });
          functions.logger.info(`Subscription cancelled: customerId=${customerId}`);
        }
        break;
      }

      default:
        functions.logger.info(`Unhandled Stripe event type: ${event.type}`);
    }
  } catch (err) {
    functions.logger.error('Error processing Stripe webhook event', err);
    return res.status(500).send('Internal error processing webhook.');
  }

  res.json({ received: true });
});

// ---------------------------------------------------------------------------
// createPortalSession
// Creates a Stripe Customer Portal session so the user can manage their
// subscription (cancel, change plan, update payment method) via Stripe's
// hosted UI. Returns a redirect URL.
// ---------------------------------------------------------------------------
exports.createPortalSession = functions.region(REGION).https.onCall({ secrets: [STRIPE_SECRET] }, async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Sign in required.');
  }

  const uid     = context.auth.uid;
  const userDoc = await db.collection('users').doc(uid).get();

  // Subscription data is stored as a map field on users/{uid} (not a subcollection)
  const customerId = userDoc.exists ? userDoc.data()?.subscription?.stripeCustomerId : null;

  if (!customerId) {
    throw new functions.https.HttpsError(
      'not-found',
      'No active subscription found. Please subscribe first.'
    );
  }

  const stripeClient = stripe(STRIPE_SECRET.value());
  const session = await stripeClient.billingPortal.sessions.create({
    customer:   customerId,
    return_url: data.returnUrl || 'https://iquizpro.com/dashboard.html',
  });

  return { url: session.url };
});

// ---------------------------------------------------------------------------
// cleanupExpiredSessions
// Scheduled daily — deletes live presenter sessions from Realtime Database
// that are older than 24 hours. Sessions must have a `createdAt` (unix ms)
// field set when created by the live presenter.
// ---------------------------------------------------------------------------
exports.cleanupExpiredSessions = functions.region(REGION)
  .pubsub.schedule('every 24 hours')
  .timeZone('Europe/London')
  .onRun(async (_context) => {
    const rtdb       = admin.database();
    const sessionsRef = rtdb.ref('sessions');
    const cutoff     = Date.now() - 24 * 60 * 60 * 1000; // 24 h ago

    // Query sessions with createdAt older than the cutoff
    const snapshot = await sessionsRef
      .orderByChild('createdAt')
      .endAt(cutoff)
      .get();

    if (!snapshot.exists()) {
      functions.logger.info('cleanupExpiredSessions: no expired sessions found');
      return null;
    }

    const deletions = {};
    snapshot.forEach(child => {
      deletions[child.key] = null; // RTDB null = delete
    });

    await sessionsRef.update(deletions);
    const count = Object.keys(deletions).length;
    functions.logger.info(`cleanupExpiredSessions: deleted ${count} expired session(s)`);
    return null;
  });
